### ISSUE TITLE
Plugin does not work in PhpStorm v8 EAP build 138.1161

### ISSUE THREAD

**Issue by bazzik** [yseasony/idea-sql-generator-tool#1]
Don't know what is wrong: it installs just fine (and used to work in previous builds) ... but after restart it is not working -- IDE complains about missing "com.intellij.persistence.database".

![screen01](https://cloud.githubusercontent.com/assets/1482298/3605419/1d885c9e-0d2b-11e4-87ac-a3ffd415b2db.png)

Not that I'm using this plugin very often (usually handling all SQL code in DB-specific tools from DB manufacturer or 3rd party) .. but I do use it from time to time for some quick stuff.

**Comment by tripflex** [comment]
yup having this same issue as well, and even made sure db navigator was installed and still get problems

**Comment by yseasony** [comment]
I will fix it as soon as possible.
Thanks

**Comment by bojoer** [comment]
Any news yet on the bugfix for the SQL Generator plugin's missing com.intellij.persistence.database?
It worked until updating to WebStorm 9 / PhpStorm 8 and mostly all other JetBrains IDE's.

Are you planning to fix this issue or is there a work around?

**Comment by hamen** [comment]
Same issue here with Intellij Idea 14 :-/

**Comment by yseasony** [comment]
https://plugins.jetbrains.com/plugin/7440
fix
update
