### ISSUE TITLE
Plugin Modification

### ISSUE THREAD

**Issue by happypaaji** [yseasony/idea-sql-generator-tool#10]
Hi, 
I wanted to modfy this / develop a similar plugin to generate some code based on a table selected from the Databases window in IntelliJ.I cloned the repository to but I am not able to build it 
<depends optional="true">com.intellij.database</depends> dependency and the com.intellij.database.view.DatabaseView class cannot be resolved.

What am I doing wrong

**Comment by yseasony** [comment]
@happypaaji 
dependencies
Contents/plugins/DatabaseTools/lib/database-impl.jar 
Contents/plugins/DatabaseTools/lib/database-openapi.jar

**Comment by yseasony** [comment]
I will change to maven project later

**Comment by happypaaji** [comment]
I should include these jars in the IntelliJ SDK or in the plugin project?
Where can I find these jars?

**Comment by yseasony** [comment]
mac
![snip20170424_79_meitu_1](https://cloud.githubusercontent.com/assets/2038344/25335258/dbd37ed2-2924-11e7-9aa0-57e47f35fcbc.jpg)
