### ISSUE TITLE
Doesn't work at all (2017.1)

### ISSUE THREAD

**Issue by bluehallu** [yseasony/idea-sql-generator-tool#11]
I tried to install this plugin with the latest version of IntelliJ Ultimate, the menu is there but whatever option I click nothing happens.

IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

**Comment by yseasony** [comment]
I try 2017.1.1,it works
![snip20170424_83](https://cloud.githubusercontent.com/assets/2038344/25336200/0182e65a-2929-11e7-823f-51e155356ed4.png)
