### ISSUE TITLE
Not seeing the select statements that are generated.

### ISSUE THREAD

**Issue by vguhesan** [yseasony/idea-sql-generator-tool#15]
I select the table and then I choose "select sql generator" but I'm not seeing the script generated. Where does it output the script?

Please advise.

IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 29, 2018
Windows 10 10.0

Sql Generator Version: 2.1.2

I am looking at the "QL Console".

I have "Database Tools and SQL" Version: 173.4548.28 (DataGrip)

**Comment by yseasony** [comment]
it’s in your clipboard

**Comment by dimalu85** [comment]
Please add this to "How to use".

Please, if possible add generated script to default (or current) console.

**Comment by yseasony** [comment]
Thank you for your advice
