### ISSUE TITLE
Add generator for insert...on duplicate key update

### ISSUE THREAD

**Issue by AlvinTheDeveloper** [yseasony/idea-sql-generator-tool#18]
We could add a new function to generate the query like this:
`INSERT... ON DUPLICATE KEY UPDATE cal_a=VALUES(cal_a), cal_b=VALUES(cal_b)`

This is a query that inserts new data if the data do not exist and update data if it already exists.
I am suggesting this because typing those "calA=VALUES(calA)" stuffs that are right after the "ON DUPLICATE KEY UPDATE" are quite time-consuming for those tables that have lots of columns.

I know maybe we would use:
`cal_c=VALUES(cal_a)+VALUES(cal_b)`
in some case. However, at least we could provide a nice template for users to edit so generating
`cal_a=VALUES(cal_a)` would be enough.

**Comment by yseasony** [comment]
https://github.com/yseasony/idea-sql-generator-tool/releases/tag/v2.2.1
