### ISSUE TITLE
Plugin not usable in DataGrip

### ISSUE THREAD

**Issue by myxor** [yseasony/idea-sql-generator-tool#5]
When installing the plugin on JetBrains DataGrip 2016.2 i get the following error:

`Plugin Error
        Problems found loading plugins:
        Plugin "Sql Generator" was not loaded: required plugin "com.intellij.database" not installed.`

Anything i can do?

**Comment by me10zyl** [comment]
same problem

**Comment by hanleybrand** [comment]
Me also 😃

**Comment by ugar0ff** [comment]
same problem in Android studio

**Comment by yseasony** [comment]
please  update. it’s fix now

**Comment by yseasony** [comment]
please  update. it’s fix now

**Comment by code-ferry** [comment]
How odd! 
I also got this error used by DataGrip 2016.3.4. 
Please check it again.

**Comment by yseasony** [comment]
@hxwabc Thanks, fixed v2.0.1
