### ISSUE TITLE
 安装成功了之后在那里打开

### ISSUE THREAD

**Issue by MissAlang** [yseasony/idea-sql-generator-tool#6]
安装成功了之后在那里打开

**Comment by me10zyl** [comment]
打开database view

**Comment by MissAlang** [comment]
我的是苹果电脑 不知道为什么不行的 哎呀

**Comment by me10zyl** [comment]
可以啊，打开database view后 在表上点击右键 就多了个选项， 看图。

**Comment by yseasony** [comment]
idea 15开始 api改变了，所以无法使用。idea 15之前的版本都可以使用 @MissAlang

**Comment by yseasony** [comment]
已经修复了，请更新下插件

**Comment by yseasony** [comment]
@MissAlang 试试最新版本
