### ISSUE TITLE
it doesn't work in datagrip

### ISSUE THREAD

**Issue by yuhan0501** [yseasony/idea-sql-generator-tool#7]
I install it in datagrip,it doesn't work.
The error like :
Problems found loading plugins: Plugin "Sql Generator" was not loaded: required plugin "com.intellij.database" not installed.

**Comment by yuhan0501** [comment]
datagrip version:2016.3.4
sql-generator-tool:2.0

**Comment by yseasony** [comment]
Thanks.
fixed v2.0.1.
